apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-api-deployment
  namespace: backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: quotes-api
  template:
    metadata:
      labels:
        app: quotes-api
    spec:
      containers:
        - name: quotes-api
          image: prashansajoshi/quotes-api:latest 
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: mysql-secret
            - configMapRef:
                name: mysql-config
          # env:
          #   # - name: MYSQL_HOST
          #   #   value: mysql 
          #   - name: MYSQL_USER
          #     value: user
          #   - name: MYSQL_PASSWORD
          #     value: password
          #   - name: MYSQL_DB
          #     value: quotesdb
          #   - name: MYSQL_HOST
          #     value: mysql.database.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: backend
spec:
  selector:
    app: quotes-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001