apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_USER: dXNlcgo= # # base64 encoded 'user'
  MYSQL_PASSWORD: cGFzc3dvcmQK # # base64 encoded 'password'
  MYSQL_ROOT_PASSWORD: cm9vdAo= # # base64 encoded 'root'


